modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "CC0-1.0"

[[mods]]
modId = "reclamation"
version = "0.1"
displayName = "Reclamation"
authors = "Lying"
description = '''
Adding more life to Minecraft through configurable decay processes
'''
#logoFile = "icon.png"

[[dependencies.reclamation]]
modId = "neoforge"
type = "required"
versionRange = "[21.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.reclamation]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.reclamation]]
modId = "architectury"
type = "required"
versionRange = "[15.0.1,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "reclamation.mixins.json"
